name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # download and build the berry interpreter
    - name: Install Berry interpreter
      run: |
        # Here you could download a prebuilt binary or clone and build Berry
        git clone https://github.com/berry-lang/berry.git
        cd berry
        make

    - name: Run tests
      run: |
        export PATH=$PATH:$PWD
        make test

    - name: Run tapp on success
      if: success()  # Only runs if previous step succeeded
      run: make tapp
